// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatisticsUpdateRequest.proto

#include "StatisticsUpdateRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace SolasMatch {
namespace Common {
namespace Protobufs {
namespace Requests {
class StatisticsUpdateRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<StatisticsUpdateRequest> _instance;
} _StatisticsUpdateRequest_default_instance_;
}  // namespace Requests
}  // namespace Protobufs
}  // namespace Common
}  // namespace SolasMatch
static void InitDefaultsscc_info_StatisticsUpdateRequest_StatisticsUpdateRequest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.DefaultConstruct();
  *::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.get_mutable() = std::string("StatisticsUpdateRequest", 23);
  ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyString(
      ::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.get_mutable());
  {
    void* ptr = &::SolasMatch::Common::Protobufs::Requests::_StatisticsUpdateRequest_default_instance_;
    new (ptr) ::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_StatisticsUpdateRequest_StatisticsUpdateRequest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_StatisticsUpdateRequest_StatisticsUpdateRequest_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_StatisticsUpdateRequest_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_StatisticsUpdateRequest_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_StatisticsUpdateRequest_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_StatisticsUpdateRequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest, class_name_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::SolasMatch::Common::Protobufs::Requests::_StatisticsUpdateRequest_default_instance_),
};

const char descriptor_table_protodef_StatisticsUpdateRequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035StatisticsUpdateRequest.proto\022$SolasMa"
  "tch.Common.Protobufs.Requests\"F\n\027Statist"
  "icsUpdateRequest\022+\n\nclass_name\030\001 \002(\t:\027St"
  "atisticsUpdateRequest"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_StatisticsUpdateRequest_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_StatisticsUpdateRequest_2eproto_sccs[1] = {
  &scc_info_StatisticsUpdateRequest_StatisticsUpdateRequest_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_StatisticsUpdateRequest_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_StatisticsUpdateRequest_2eproto = {
  false, false, descriptor_table_protodef_StatisticsUpdateRequest_2eproto, "StatisticsUpdateRequest.proto", 141,
  &descriptor_table_StatisticsUpdateRequest_2eproto_once, descriptor_table_StatisticsUpdateRequest_2eproto_sccs, descriptor_table_StatisticsUpdateRequest_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_StatisticsUpdateRequest_2eproto::offsets,
  file_level_metadata_StatisticsUpdateRequest_2eproto, 1, file_level_enum_descriptors_StatisticsUpdateRequest_2eproto, file_level_service_descriptors_StatisticsUpdateRequest_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_StatisticsUpdateRequest_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_StatisticsUpdateRequest_2eproto)), true);
namespace SolasMatch {
namespace Common {
namespace Protobufs {
namespace Requests {

// ===================================================================

void StatisticsUpdateRequest::InitAsDefaultInstance() {
}
class StatisticsUpdateRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<StatisticsUpdateRequest>()._has_bits_);
  static void set_has_class_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_;
StatisticsUpdateRequest::StatisticsUpdateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
}
StatisticsUpdateRequest::StatisticsUpdateRequest(const StatisticsUpdateRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  class_name_.UnsafeSetDefault(&::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.get());
  if (from._internal_has_class_name()) {
    class_name_.Set(&::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.get(), from._internal_class_name(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
}

void StatisticsUpdateRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_StatisticsUpdateRequest_StatisticsUpdateRequest_2eproto.base);
  class_name_.UnsafeSetDefault(&::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.get());
}

StatisticsUpdateRequest::~StatisticsUpdateRequest() {
  // @@protoc_insertion_point(destructor:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void StatisticsUpdateRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  class_name_.DestroyNoArena(&::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.get());
}

void StatisticsUpdateRequest::ArenaDtor(void* object) {
  StatisticsUpdateRequest* _this = reinterpret_cast< StatisticsUpdateRequest* >(object);
  (void)_this;
}
void StatisticsUpdateRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void StatisticsUpdateRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const StatisticsUpdateRequest& StatisticsUpdateRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_StatisticsUpdateRequest_StatisticsUpdateRequest_2eproto.base);
  return *internal_default_instance();
}


void StatisticsUpdateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    class_name_.ClearToDefault(&::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.get(), GetArena());
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StatisticsUpdateRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required string class_name = 1 [default = "StatisticsUpdateRequest"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_class_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest.class_name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* StatisticsUpdateRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string class_name = 1 [default = "StatisticsUpdateRequest"];
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_class_name().data(), static_cast<int>(this->_internal_class_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest.class_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_class_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  return target;
}

size_t StatisticsUpdateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  size_t total_size = 0;

  // required string class_name = 1 [default = "StatisticsUpdateRequest"];
  if (_internal_has_class_name()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_class_name());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StatisticsUpdateRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const StatisticsUpdateRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<StatisticsUpdateRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
    MergeFrom(*source);
  }
}

void StatisticsUpdateRequest::MergeFrom(const StatisticsUpdateRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_class_name()) {
    _internal_set_class_name(from._internal_class_name());
  }
}

void StatisticsUpdateRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StatisticsUpdateRequest::CopyFrom(const StatisticsUpdateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SolasMatch.Common.Protobufs.Requests.StatisticsUpdateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StatisticsUpdateRequest::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void StatisticsUpdateRequest::InternalSwap(StatisticsUpdateRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  class_name_.Swap(&other->class_name_, &::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest::_i_give_permission_to_break_this_code_default_class_name_.get(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata StatisticsUpdateRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Requests
}  // namespace Protobufs
}  // namespace Common
}  // namespace SolasMatch
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest* Arena::CreateMaybeMessage< ::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SolasMatch::Common::Protobufs::Requests::StatisticsUpdateRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
