#ifndef EMAILPLUGIN_GLOBAL_H
#define EMAILPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EMAILPLUGIN_LIBRARY)
#  define EMAILPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EMAILPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EMAILPLUGIN_GLOBAL_H
