struct trommons_pair {
    std::string language;
    std::string language_code;
    std::string country_code;
};

struct trommons_pair from_neon_to_trommons_pair[] = {
    {"Afrikaans", "af", "ZA"},
    {"Albanian", "sq", "--"},
    {"Amharic", "am", "ET"},
    {"Arabic", "ar", "SA"},
    {"Armenian", "hy", "AM"},
    {"Azerbaijani (Cyrillic)", "az", "91"},
    {"Azerbaijani (Latin)", "az", "90"},
    {"Aymara", "ay", "--"},
    {"Basque", "eu", "--"},
    {"Bengali (India)", "bn", "IN"},
    {"Bengali (Bangladesh)", "bn", "BD"},
    {"Belarus", "be", "BY"},
    {"Bosnian (Cyrillic)", "bs", "91"},
    {"Bosnian (Latin)", "bs", "90"},
    {"Bulgarian", "bg", "--"},
    {"Burmese", "my", "MM"},
    {"Catalan", "ca", "--"},
    {"Cebuano", "ceb", "PH"},
    {"Chinese Simplified", "zh", "92"},
    {"Chinese Traditional", "zh", "93"},
    {"Croatian", "hr", "--"},
    {"Czech", "cs", "--"},
    {"Danish", "da", "--"},
    {"Dutch", "nl", "--"},
    {"English", "en", "GB"},
    {"English US", "en", "US"},
    {"Estonian", "et", "--"},
    {"Fula", "ff", "--"},
    {"Finnish", "fi", "--"},
    {"French", "fr", "FR"},
    {"French Canada", "fr", "CA"},
    {"French Congo", "fr", "CD"},
    {"Galician", "gl", "--"},
    {"Georgian", "ka", "GE"},
    {"German", "de", "--"},
    {"Greek", "el", "--"},
    {"Gujarati", "gu", "IN"},
    {"Haitian Creole French", "ht", "HT"},
    {"Hausa", "ha", "NG"},
    {"Hebrew", "he", "--"},
    {"Hindi", "hi", "IN"},
    {"Hungarian", "hu", "--"},
    {"Icelandic", "is", "--"},
    {"Indonesian", "id", "ID"},
    {"Irish Gaelic", "ga", "--"},
    {"Italian", "it", "--"},
    {"Japanese", "ja", "--"},
    {"Kanuri", "kr", "--"},
    {"Kazakh", "kk", "KZ"},
    {"Khmer", "km", "KH"},
    {"Korean", "ko", "KR"},
    {"Kurdish Kurmanji", "kmr", "--"},
    {"Kurdish Bahdini", "kmr", "94"},
    {"Kurdish Sorani", "ckb", "--"},
    {"Kyrgyz", "ky", "KG"},
    {"Latvian", "lv", "--"},
    {"Lingala", "ln", "--"},
    {"Lingala Makanja", "ln", "CD"},
    {"Lithuanian", "lt", "--"},
    {"Macedonian", "mk", "MK"},
    {"Malagasy", "mg", "MG"},
    {"Malay", "ms", "MY"},
    {"Malayalam", "ml", "IN"},
    {"Maltese", "mt", "MT"},
    {"Maori", "mi", "NZ"},
    {"Mongolian", "mn", "MN"},
    {"Nepali", "ne", "NP"},
    {"Nyanja/Chewa", "ny", "--"},
    {"Punjabi (Gurmukhi, India)", "pa", "IN"},
    {"Punjabi (Shahmukhi, Pakistan)", "pa", "PK"},
    {"Pashto", "ps", "PK"},
    {"Pashto (Afghanistan)", "ps", "AF"},
    {"Dari", "prs", "AF"},
    {"Persian", "fa", "IR"},
    {"Polish", "pl", "--"},
    {"Portuguese", "pt", "PT"},
    {"Portuguese Brazil", "pt", "BR"},
    {"Quechua", "qu", "--"},
    {"Rohingya (Latin)", "rhg", "90"},
    {"Rohingya (Bangla)", "rhg", "95"},
    {"Romanian", "ro", "--"},
    {"Russian", "ru", "RU"},
    {"Serbian (Latin)", "sr", "90"},
    {"Serbian (Cyrilic)", "sr", "91"},
    {"Montenegrin Latin", "cnr", "90"},
    {"Montenegrin Cyrillic", "cnr", "91"},
    {"Sotho Northern", "nso", "ZA"},
    {"Setswana (South Africa)", "tn", "BW"},
    {"Slovak", "sk", "--"},
    {"Slovenian", "sl", "--"},
    {"Somali (Ethiopia)", "so", "ET"},
    {"Somali (Somalia)", "so", "SO"},
    {"Spanish", "es", "ES"},
    {"Spanish Latin America", "es", "49"},
    {"Spanish Mexico", "es", "MX"},
    {"Spanish Colombia", "es", "CO"},
    {"Swahili", "sw", "--"},
    {"Swedish", "sv", "--"},
    {"Tagalog", "tl", "PH"},
    {"Tamil (India)", "ta", "IN"},
    {"Tamil (Sri Lanka)", "ta", "LK"},
    {"Telugu", "te", "--"},
    {"Tatar", "tt", "RU"},
    {"Thai", "th", "TH"},
    {"Tigre", "tig", "--"},
    {"Tigrinya", "ti", "--"},
    {"Tsonga", "ts", "ZA"},
    {"Turkish", "tr", "--"},
    {"Turkmen", "tk", "TM"},
    {"Ukrainian", "uk", "UA"},
    {"Urdu", "ur", "PK"},
    {"Uzbek", "uz", "91"},
    {"Vietnamese", "vi", "VN"},
    {"Welsh", "cy", "GB"},
    {"Xhosa", "xh", "ZA"},
    {"Yoruba", "yo", "NG"},
    {"Zarma", "dje", "--"},
    {"Zulu", "zu", "ZA"},
    {"Hmong", "hmn", "--"},
    {"Karen", "kar", "MM"},
    {"Rundi", "run", "BI"},
    {"Assamese", "asm", "IN"},
    {"Konkani", "kok", "IN"},
    {"Chadian Arabic", "shu", "TD"},
    {"Chadian Arabic Latin", "shu", "90"},
    {"Kamba", "kam", "KE"},
    {"Marghi Central", "mrt", "NG"},
    {"Kalenjin", "kln", "KE"},
    {"Luba-Katanga", "lu", "--"},
    {"Luo", "luo", "KE"},
    {"Kikuyu", "ki", "KE"},
    {"Kisii", "guz", "KE"},
    {"Fijian", "fj", "--"},
    {"Bislama", "bi", "--"},
    {"Tok Pisin", "tpi", "PG"},
    {"Tongan", "to", "TO"},
    {"Bemba", "bem", "ZM"},
    {"Tibetan", "bo", "--"},
    {"Dhivehi", "dv", "MV"},
    {"Filipino", "fil", "PH"},
    {"Kabuverdianu", "kea", "CV"},
    {"Norwegian Bokmål", "no", "--"},
    {"Norwegian Nynorsk", "nn", "--"},
    {"Pijin", "pis", "SB"},
    {"Kinyarwanda", "rw", "RW"},
    {"Sango", "sg", "CF"},
    {"Samoan", "sm", "WS"},
    {"Shona", "sn", "ZW"},
    {"Sotho Southern", "st", "LS"},
    {"Tswana", "tn", "BW"},
    {"Wolof", "wo", "SN"},
    {"Chittagonian", "ctg", "BD"},
    {"Ganda", "lg", "--"},
    {"Sena", "seh", "ZW"},
    {"Ndau", "ndc", "--"},
    {"Marathi", "mr", "IN"},
    {"Kannada", "kn", "IN"},
    {"Portuguese Mozambique", "pt", "MZ"},
    {"Glavda", "glw", "NG"},
    {"Higi", "hig", "NG"},
    {"Mandara", "mfi", "CM"},
    {"Gamargu (Nigeria)", "mf0", "NG"},
    {"Bura-Pabir", "bwr", "NG"},
    {"Kibaku", "ckl", "NG"},
    {"Lamang", "hia", "NG"},
    {"Levantine Arabic", "apc", "--"},
    {"Swahili Congo", "swc", "CD"},
    {"Afar", "aa", "ET"},
    {"Arabic Juba", "pga", "--"},
    {"Chechen", "ce", "RU"},
    {"Dinka", "din", "SS"},
    {"Edo", "bin", "NG"},
    {"Guaraní", "gn", "PY"},
    {"Hiligaynon", "hil", "PH"},
    {"Igbo", "ig", "NG"},
    {"Ilocano", "ilo", "PH"},
    {"K'iche'", "quc", "GT"},
    {"Kongo", "kg", "CG"},
    {"Ndebele South", "nr", "--"},
    {"Ndebele North", "nd", "--"},
    {"Sindhi", "sd", "IN"},
    {"Sindhi (Arabic)", "sd", "PK"},
    {"Sinhala", "si", "LK"},
    {"Sylheti", "syl", "BD"},
    {"Tajik", "tg", "91"},
    {"Dyula", "dyu", "--"},
    {"Nande", "nnb", "CD"},
    {"Shi", "shr", "CD"},
    {"Lao", "lo", "--"},
    {"Oromo", "om", "ET"},
    {"Mongo", "lol", "CD"},
    {"Ngombe", "ngc", "CD"},
    {"Nuer", "nus", "SS"},
    {"Krio", "kri", "SL"},
    {"Tshiluba", "lua", "CD"},
    {"Tausug", "tsg", "PH"},
    {"Maranao", "mrw", "PH"},
    {"Maguindanao", "mdh", "PH"},
    {"Chavacano", "cbk", "PH"},
    {"Waray", "war", "PH"},
    {"Bikol", "bik", "PH"},
    {"Kapampangan", "pam", "PH"},
    {"Pangasinan", "pag", "PH"},
    {"Twi", "tw", "--"},
    {"Bambara", "bm", "--"},
    {"Tamasheq (Mali)", "taq", "ML"},
    {"Pidgin (Nigeria)", "pcm", "NG"},
    {"Tene Kan Dogon", "dtk", "--"},
    {"Koyraboro Senni Songhay", "ses", "--"},
    {"Romani", "rom", "--"}
};
int from_neon_to_trommons_pair_count = 210;
