// php /mnt/c/Users/Alan/Dropbox/Backup/generate_from_neon_to_trommons_pair.php

// ( C:\Users\Alan\Dropbox\Backup\generate_from_neon_to_trommons_pair.php )
// Generates: /mnt/c/Users/Alan/OneDrive/Desktop/from_neon_to_trommons_pair.h
// Goes to:   C:\gitrosetta\backend\EmailPlugin\Generators\from_neon_to_trommons_pair.h

struct trommons_pair {
    std::string language;
    std::string language_code;
    std::string country_code;
};

struct trommons_pair from_neon_to_trommons_pair[] = {
    {"Afrikaans", "af", "ZA"},
    {"Albanian", "sq", "--"},
    {"Amharic", "am", "ET"},
    {"Arabic", "ar", "SA"},
    {"Armenian", "hy", "AM"},
    {"Azerbaijani Cyrillic", "az", "91"},
    {"Azerbaijani Latin", "az", "90"},
    {"Aymara", "ay", "--"},
    {"Basque", "eu", "--"},
    {"Bengali, India", "bn", "IN"},
    {"Bengali", "bn", "BD"},
    {"Belarusian", "be", "BY"},
    {"Bosnian Cyrillic", "bs", "91"},
    {"Bosnian Latin", "bs", "90"},
    {"Bulgarian", "bg", "--"},
    {"Burmese", "my", "MM"},
    {"Catalan", "ca", "--"},
    {"Cebuano", "ceb", "--"},
    {"Chinese Simplified", "zh", "92"},
    {"Chinese Traditional", "zh", "93"},
    {"Croatian", "hr", "--"},
    {"Czech", "cs", "--"},
    {"Danish", "da", "--"},
    {"Dutch", "nl", "--"},
    {"English", "en", "GB"},
    {"English, US", "en", "US"},
    {"Estonian", "et", "--"},
    {"Fulah", "ff", "--"},
    {"Finnish", "fi", "--"},
    {"French", "fr", "FR"},
    {"French, Canada", "fr", "CA"},
    {"French, Congo", "fr", "CD"},
    {"Galician", "gl", "--"},
    {"Georgian", "ka", "GE"},
    {"German", "de", "--"},
    {"Greek", "el", "--"},
    {"Gujarati", "gu", "IN"},
    {"Haitian", "ht", "--"},
    {"Hausa", "ha", "--"},
    {"Hebrew", "he", "--"},
    {"Hindi", "hi", "IN"},
    {"Hungarian", "hu", "--"},
    {"Icelandic", "is", "--"},
    {"Indonesian", "id", "ID"},
    {"Irish Gaelic", "ga", "--"},
    {"Italian", "it", "--"},
    {"Japanese", "ja", "--"},
    {"Kanuri", "kr", "--"},
    {"Kazakh", "kk", "KZ"},
    {"Khmer", "km", "--"},
    {"Korean", "ko", "KR"},
    {"Kurdish Kurmanji", "kmr", "--"},
    {"Kurdish Bahdini", "kmr", "94"},
    {"Kurdish Sorani", "ckb", "--"},
    {"Kirghiz", "ky", "KG"},
    {"Latvian", "lv", "--"},
    {"Lingala", "ln", "--"},
    {"Lingala, Makanja", "ln", "CD"},
    {"Lithuanian", "lt", "--"},
    {"Macedonian", "mk", "MK"},
    {"Malagasy", "mg", "MG"},
    {"Malay", "ms", "MY"},
    {"Malayalam", "ml", "IN"},
    {"Maltese", "mt", "MT"},
    {"Maori", "mi", "NZ"},
    {"Mongolian", "mn", "MN"},
    {"Nepali", "ne", "NP"},
    {"Nyanja/Chewa", "ny", "--"},
    {"Panjabi Gurmukhi", "pa", "IN"},
    {"Panjabi Shahmukhi", "pa", "PK"},
    {"Pushto, Pakistan", "ps", "--"},
    {"Pushto", "ps", "AF"},
    {"Dari", "prs", "AF"},
    {"Persian", "fa", "IR"},
    {"Polish", "pl", "--"},
    {"Portuguese", "pt", "PT"},
    {"Portuguese, Brazil", "pt", "BR"},
    {"Quechua", "qu", "--"},
    {"Rohingya Latin", "rhg", "90"},
    {"Rohingya Bengali", "rhg", "95"},
    {"Romanian", "ro", "--"},
    {"Russian", "ru", "RU"},
    {"Serbian Latin", "sr", "90"},
    {"Serbian Cyrilic", "sr", "91"},
    {"Montenegrin Latin", "cnr", "90"},
    {"Montenegrin Cyrillic", "cnr", "91"},
    {"Northern Sotho", "nso", "--"},
    {"Slovak", "sk", "--"},
    {"Slovenian", "sl", "--"},
    {"Somali, Ethiopia", "so", "ET"},
    {"Somali", "so", "SO"},
    {"Spanish", "es", "ES"},
    {"Spanish, Latin America", "es", "49"},
    {"Spanish, Colombia", "es", "CO"},
    {"Swahili", "sw", "--"},
    {"Swedish", "sv", "--"},
    {"Tagalog", "tl", "--"},
    {"Tamil", "ta", "IN"},
    {"Tamil, Sri Lanka", "ta", "LK"},
    {"Telugu", "te", "--"},
    {"Tatar", "tt", "--"},
    {"Thai", "th", "TH"},
    {"Tigre", "tig", "--"},
    {"Tigrinya", "ti", "--"},
    {"Tsonga", "ts", "--"},
    {"Turkish", "tr", "--"},
    {"Turkmen", "tk", "--"},
    {"Ukrainian", "uk", "UA"},
    {"Urdu", "ur", "PK"},
    {"Uzbek", "uz", "91"},
    {"Vietnamese", "vi", "VN"},
    {"Welsh", "cy", "GB"},
    {"Xhosa", "xh", "--"},
    {"Yoruba", "yo", "--"},
    {"Zarma", "dje", "--"},
    {"Zulu", "zu", "ZA"},
    {"Hmong", "hmn", "--"},
    {"Karen", "kar", "--"},
    {"Rundi", "run", "BI"},
    {"Assamese", "asm", "--"},
    {"Konkani", "kok", "--"},
    {"Chadian Arabic", "shu", "TD"},
    {"Chadian Arabic Latin", "shu", "90"},
    {"Kamba", "kam", "KE"},
    {"Marghi Central", "mrt", "--"},
    {"Kalenjin", "kln", "KE"},
    {"Luba-Katanga", "lu", "--"},
    {"Luo", "luo", "KE"},
    {"Kikuyu", "ki", "--"},
    {"Gusii", "guz", "KE"},
    {"Fijian", "fj", "--"},
    {"Bislama", "bi", "--"},
    {"Tok Pisin", "tpi", "--"},
    {"Tonga", "to", "--"},
    {"Bemba", "bem", "--"},
    {"Tibetan", "bo", "--"},
    {"Dhivehi", "dv", "MV"},
    {"Filipino", "fil", "PH"},
    {"Kabuverdianu", "kea", "CV"},
    {"Norwegian Bokmål", "no", "--"},
    {"Norwegian Nynorsk", "nn", "--"},
    {"Pijin", "pis", "--"},
    {"Kinyarwanda", "rw", "--"},
    {"Sango", "sg", "CF"},
    {"Samoan", "sm", "--"},
    {"Shona", "sn", "--"},
    {"Southern Sotho", "st", "--"},
    {"Tswana", "tn", "--"},
    {"Wolof", "wo", "SN"},
    {"Chittagonian", "ctg", "BD"},
    {"Ganda", "lg", "--"},
    {"Sena", "seh", "--"},
    {"Ndau", "ndc", "--"},
    {"Marathi", "mr", "IN"},
    {"Kannada", "kn", "IN"},
    {"Portuguese, Mozambique", "pt", "MZ"},
    {"Glavda", "glw", "--"},
    {"Kamwe", "hig", "--"},
    {"Wandala", "mfi", "CM"},
    {"Gamargu", "mf0", "NG"},
    {"Bura-Pabir", "bwr", "--"},
    {"Kibaku", "ckl", "--"},
    {"Lamang", "hia", "--"},
    {"Arabic, North Levantine", "apc", "--"},
    {"Swahili, Congo", "swc", "CD"},
    {"Afar", "aa", "--"},
    {"Juba Arabic", "pga", "--"},
    {"Chechen", "ce", "RU"},
    {"Dinka", "din", "SS"},
    {"Bini/Edo", "bin", "NG"},
    {"Guaraní", "gn", "--"},
    {"Hiligaynon", "hil", "--"},
    {"Igbo", "ig", "NG"},
    {"Iloko", "ilo", "PH"},
    {"K'iche'", "quc", "--"},
    {"Kongo", "kg", "--"},
    {"Ndebele, South", "nr", "--"},
    {"Ndebele, North", "nd", "--"},
    {"Sindhi Devenagari", "sd", "--"},
    {"Sindhi Arabic", "sd", "PK"},
    {"Sinhala", "si", "LK"},
    {"Sylheti", "syl", "--"},
    {"Tajik", "tg", "91"},
    {"Dyula", "dyu", "--"},
    {"Nande", "nnb", "--"},
    {"Shi", "shr", "--"},
    {"Lao", "lo", "--"},
    {"Oromo", "om", "ET"},
    {"Mongo", "lol", "--"},
    {"Ngombe", "ngc", "--"},
    {"Nuer", "nus", "--"},
    {"Krio", "kri", "--"},
    {"Luba-Lulua", "lua", "--"},
    {"Tausug", "tsg", "PH"},
    {"Maranao", "mrw", "--"},
    {"Maguindanaon", "mdh", "--"},
    {"Chavacano", "cbk", "--"},
    {"Waray", "war", "--"},
    {"Bikol", "bik", "--"},
    {"Pampanga", "pam", "--"},
    {"Pangasinan", "pag", "--"},
    {"Twi", "tw", "--"},
    {"Bambara", "bm", "--"},
    {"Tamasheq", "taq", "ML"},
    {"Nigerian Pidgin", "pcm", "NG"},
    {"Dogon, Tene Kan", "dtk", "--"},
    {"Songhay, Koyraboro Senni", "ses", "--"},
    {"Romani", "rom", "--"}
};
int from_neon_to_trommons_pair_count = 208;
