// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BannedLogin.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "BannedLogin.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SolasMatch {
namespace Common {
namespace Protobufs {
namespace Emails {

namespace {

const ::google::protobuf::Descriptor* BannedLogin_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BannedLogin_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_BannedLogin_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_BannedLogin_2eproto() {
  protobuf_AddDesc_BannedLogin_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "BannedLogin.proto");
  GOOGLE_CHECK(file != NULL);
  BannedLogin_descriptor_ = file->message_type(0);
  static const int BannedLogin_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BannedLogin, email_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BannedLogin, user_id_),
  };
  BannedLogin_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      BannedLogin_descriptor_,
      BannedLogin::default_instance_,
      BannedLogin_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BannedLogin, _has_bits_[0]),
      -1,
      -1,
      sizeof(BannedLogin),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BannedLogin, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_BannedLogin_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      BannedLogin_descriptor_, &BannedLogin::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_BannedLogin_2eproto() {
  delete BannedLogin::default_instance_;
  delete BannedLogin_reflection_;
}

void protobuf_AddDesc_BannedLogin_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_BannedLogin_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::SolasMatch::Common::Protobufs::Emails::protobuf_AddDesc_EmailMessage_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021BannedLogin.proto\022\"SolasMatch.Common.P"
    "rotobufs.Emails\032\022EmailMessage.proto\"v\n\013B"
    "annedLogin\022V\n\nemail_type\030\001 \002(\01625.SolasMa"
    "tch.Common.Protobufs.Emails.EmailMessage"
    ".Type:\013BannedLogin\022\017\n\007user_id\030\002 \001(\005", 195);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "BannedLogin.proto", &protobuf_RegisterTypes);
  BannedLogin::default_instance_ = new BannedLogin();
  BannedLogin::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_BannedLogin_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_BannedLogin_2eproto {
  StaticDescriptorInitializer_BannedLogin_2eproto() {
    protobuf_AddDesc_BannedLogin_2eproto();
  }
} static_descriptor_initializer_BannedLogin_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BannedLogin::kEmailTypeFieldNumber;
const int BannedLogin::kUserIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BannedLogin::BannedLogin()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SolasMatch.Common.Protobufs.Emails.BannedLogin)
}

void BannedLogin::InitAsDefaultInstance() {
}

BannedLogin::BannedLogin(const BannedLogin& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SolasMatch.Common.Protobufs.Emails.BannedLogin)
}

void BannedLogin::SharedCtor() {
  _cached_size_ = 0;
  email_type_ = 14;
  user_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BannedLogin::~BannedLogin() {
  // @@protoc_insertion_point(destructor:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  SharedDtor();
}

void BannedLogin::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BannedLogin::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BannedLogin::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BannedLogin_descriptor_;
}

const BannedLogin& BannedLogin::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_BannedLogin_2eproto();
  return *default_instance_;
}

BannedLogin* BannedLogin::default_instance_ = NULL;

BannedLogin* BannedLogin::New(::google::protobuf::Arena* arena) const {
  BannedLogin* n = new BannedLogin;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BannedLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  if (_has_bits_[0 / 32] & 3u) {
    email_type_ = 14;
    user_id_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool BannedLogin::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .SolasMatch.Common.Protobufs.Emails.EmailMessage.Type email_type = 1 [default = BannedLogin];
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::SolasMatch::Common::Protobufs::Emails::EmailMessage_Type_IsValid(value)) {
            set_email_type(static_cast< ::SolasMatch::Common::Protobufs::Emails::EmailMessage_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_user_id;
        break;
      }

      // optional int32 user_id = 2;
      case 2: {
        if (tag == 16) {
         parse_user_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  return false;
#undef DO_
}

void BannedLogin::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  // required .SolasMatch.Common.Protobufs.Emails.EmailMessage.Type email_type = 1 [default = BannedLogin];
  if (has_email_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->email_type(), output);
  }

  // optional int32 user_id = 2;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->user_id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:SolasMatch.Common.Protobufs.Emails.BannedLogin)
}

::google::protobuf::uint8* BannedLogin::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  // required .SolasMatch.Common.Protobufs.Emails.EmailMessage.Type email_type = 1 [default = BannedLogin];
  if (has_email_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->email_type(), target);
  }

  // optional int32 user_id = 2;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->user_id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  return target;
}

int BannedLogin::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  int total_size = 0;

  // required .SolasMatch.Common.Protobufs.Emails.EmailMessage.Type email_type = 1 [default = BannedLogin];
  if (has_email_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->email_type());
  }
  // optional int32 user_id = 2;
  if (has_user_id()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->user_id());
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BannedLogin::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const BannedLogin* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const BannedLogin>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SolasMatch.Common.Protobufs.Emails.BannedLogin)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SolasMatch.Common.Protobufs.Emails.BannedLogin)
    MergeFrom(*source);
  }
}

void BannedLogin::MergeFrom(const BannedLogin& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_email_type()) {
      set_email_type(from.email_type());
    }
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void BannedLogin::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BannedLogin::CopyFrom(const BannedLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SolasMatch.Common.Protobufs.Emails.BannedLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BannedLogin::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void BannedLogin::Swap(BannedLogin* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BannedLogin::InternalSwap(BannedLogin* other) {
  std::swap(email_type_, other->email_type_);
  std::swap(user_id_, other->user_id_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BannedLogin::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BannedLogin_descriptor_;
  metadata.reflection = BannedLogin_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BannedLogin

// required .SolasMatch.Common.Protobufs.Emails.EmailMessage.Type email_type = 1 [default = BannedLogin];
bool BannedLogin::has_email_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void BannedLogin::set_has_email_type() {
  _has_bits_[0] |= 0x00000001u;
}
void BannedLogin::clear_has_email_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void BannedLogin::clear_email_type() {
  email_type_ = 14;
  clear_has_email_type();
}
 ::SolasMatch::Common::Protobufs::Emails::EmailMessage_Type BannedLogin::email_type() const {
  // @@protoc_insertion_point(field_get:SolasMatch.Common.Protobufs.Emails.BannedLogin.email_type)
  return static_cast< ::SolasMatch::Common::Protobufs::Emails::EmailMessage_Type >(email_type_);
}
 void BannedLogin::set_email_type(::SolasMatch::Common::Protobufs::Emails::EmailMessage_Type value) {
  assert(::SolasMatch::Common::Protobufs::Emails::EmailMessage_Type_IsValid(value));
  set_has_email_type();
  email_type_ = value;
  // @@protoc_insertion_point(field_set:SolasMatch.Common.Protobufs.Emails.BannedLogin.email_type)
}

// optional int32 user_id = 2;
bool BannedLogin::has_user_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void BannedLogin::set_has_user_id() {
  _has_bits_[0] |= 0x00000002u;
}
void BannedLogin::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000002u;
}
void BannedLogin::clear_user_id() {
  user_id_ = 0;
  clear_has_user_id();
}
 ::google::protobuf::int32 BannedLogin::user_id() const {
  // @@protoc_insertion_point(field_get:SolasMatch.Common.Protobufs.Emails.BannedLogin.user_id)
  return user_id_;
}
 void BannedLogin::set_user_id(::google::protobuf::int32 value) {
  set_has_user_id();
  user_id_ = value;
  // @@protoc_insertion_point(field_set:SolasMatch.Common.Protobufs.Emails.BannedLogin.user_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Emails
}  // namespace Protobufs
}  // namespace Common
}  // namespace SolasMatch

// @@protoc_insertion_point(global_scope)
