// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaskScoreEmail.proto

#ifndef PROTOBUF_TaskScoreEmail_2eproto__INCLUDED
#define PROTOBUF_TaskScoreEmail_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "EmailMessage.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TaskScoreEmail_2eproto();
void protobuf_AssignDesc_TaskScoreEmail_2eproto();
void protobuf_ShutdownFile_TaskScoreEmail_2eproto();

class TaskScoreEmail;

// ===================================================================

class TaskScoreEmail : public ::google::protobuf::Message {
 public:
  TaskScoreEmail();
  virtual ~TaskScoreEmail();
  
  TaskScoreEmail(const TaskScoreEmail& from);
  
  inline TaskScoreEmail& operator=(const TaskScoreEmail& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const TaskScoreEmail& default_instance();
  
  void Swap(TaskScoreEmail* other);
  
  // implements Message ----------------------------------------------
  
  TaskScoreEmail* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TaskScoreEmail& from);
  void MergeFrom(const TaskScoreEmail& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .EmailMessage.Type email_type = 1 [default = TaskScoreEmail];
  inline bool has_email_type() const;
  inline void clear_email_type();
  static const int kEmailTypeFieldNumber = 1;
  inline ::EmailMessage_Type email_type() const;
  inline void set_email_type(::EmailMessage_Type value);
  
  // required string body = 2;
  inline bool has_body() const;
  inline void clear_body();
  static const int kBodyFieldNumber = 2;
  inline const ::std::string& body() const;
  inline void set_body(const ::std::string& value);
  inline void set_body(const char* value);
  inline void set_body(const char* value, size_t size);
  inline ::std::string* mutable_body();
  inline ::std::string* release_body();
  
  // @@protoc_insertion_point(class_scope:TaskScoreEmail)
 private:
  inline void set_has_email_type();
  inline void clear_has_email_type();
  inline void set_has_body();
  inline void clear_has_body();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* body_;
  int email_type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_TaskScoreEmail_2eproto();
  friend void protobuf_AssignDesc_TaskScoreEmail_2eproto();
  friend void protobuf_ShutdownFile_TaskScoreEmail_2eproto();
  
  void InitAsDefaultInstance();
  static TaskScoreEmail* default_instance_;
};
// ===================================================================


// ===================================================================

// TaskScoreEmail

// required .EmailMessage.Type email_type = 1 [default = TaskScoreEmail];
inline bool TaskScoreEmail::has_email_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TaskScoreEmail::set_has_email_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TaskScoreEmail::clear_has_email_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TaskScoreEmail::clear_email_type() {
  email_type_ = 1;
  clear_has_email_type();
}
inline ::EmailMessage_Type TaskScoreEmail::email_type() const {
  return static_cast< ::EmailMessage_Type >(email_type_);
}
inline void TaskScoreEmail::set_email_type(::EmailMessage_Type value) {
  GOOGLE_DCHECK(::EmailMessage_Type_IsValid(value));
  set_has_email_type();
  email_type_ = value;
}

// required string body = 2;
inline bool TaskScoreEmail::has_body() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TaskScoreEmail::set_has_body() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TaskScoreEmail::clear_has_body() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TaskScoreEmail::clear_body() {
  if (body_ != &::google::protobuf::internal::kEmptyString) {
    body_->clear();
  }
  clear_has_body();
}
inline const ::std::string& TaskScoreEmail::body() const {
  return *body_;
}
inline void TaskScoreEmail::set_body(const ::std::string& value) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    body_ = new ::std::string;
  }
  body_->assign(value);
}
inline void TaskScoreEmail::set_body(const char* value) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    body_ = new ::std::string;
  }
  body_->assign(value);
}
inline void TaskScoreEmail::set_body(const char* value, size_t size) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    body_ = new ::std::string;
  }
  body_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskScoreEmail::mutable_body() {
  set_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    body_ = new ::std::string;
  }
  return body_;
}
inline ::std::string* TaskScoreEmail::release_body() {
  clear_has_body();
  if (body_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = body_;
    body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TaskScoreEmail_2eproto__INCLUDED
